
development:
  secret_key_base: dcaf24a687b5daa32a2a8612b2f9620382c40b3df0e2c34c5ef91d83ecd3b2a608736781f668b28e1f572dd1ae3022273d93b74a0f5c5af2a9813d6b1cd98718
  twilio_sid: 'twilio_sid'
  twilio_token: 'twilio_token'
  twilio_number: 'twilio_number'

test:
  secret_key_base: 471a3156ff6d3ac4f1486fdd616d675b595e46bc56033f41921fc4257a44d66f618907c89523691b0663fe0a7bd5cbbc8cdba287263bfbd6c23c5ff12e3cd869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: = ENV["SECRET_KEY_BASE"]
  twilio_sid:  = ENV["TWILIO_SID"]
  twilio_token:  = ENV["TWILIO_TOKEN"]
  twilio_number:  = ENV["TWILIO_NUMBER"]

